apiVersion: v1
kind: Secret
metadata:
  name: dockerhub-credential
  annotations:
    tekton.dev/docker-0: https://index.docker.io/v1/
type: kubernetes.io/basic-auth
stringData:
    username: <your_username_here>
    password: <your-password-here>
