apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: taskrun-build-push
spec:
  serviceAccountName: pipeline
  taskRef:
    name: sampletask
  params:
    - name: pathToDockerFile
      value: Dockerfile
  resources:
    inputs:
      - name: docker-source
        resourceRef:
          name: git-input
    outputs:
      - name: builtImage
        resourceRef:
          name: imageurl
