apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  labels:
    app: test
spec:
  containers:
  - name: ubuntu
    image: ubuntu:latest
    command: ["curl", "localhost:5000/app:0.0.1"]
    args: ["-c", "while true; do echo hello; sleep 10;done"]
